#############################################################################
# Makefile for building: QTLife.app/Contents/MacOS/QTLife
# Generated by qmake (3.0) (Qt 5.1.1) on: Tue Sep 10 00:13:45 2013
# Project:  QTLife.pro
# Template: app
# Command: /Users/anthonypray/Qt/5.1.1/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile QTLife.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../Qt/5.1.1/clang_64/mkspecs/macx-clang -I. -Iqtquick2applicationviewer -I../Qt/5.1.1/clang_64/include -I../Qt/5.1.1/clang_64/include/QtQuick -I../Qt/5.1.1/clang_64/lib/QtQuick.framework/Versions/5/Headers -I../Qt/5.1.1/clang_64/include/QtQml -I../Qt/5.1.1/clang_64/lib/QtQml.framework/Versions/5/Headers -I../Qt/5.1.1/clang_64/include/QtNetwork -I../Qt/5.1.1/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../Qt/5.1.1/clang_64/include/QtGui -I../Qt/5.1.1/clang_64/lib/QtGui.framework/Versions/5/Headers -I../Qt/5.1.1/clang_64/include/QtCore -I../Qt/5.1.1/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/anthonypray/Qt/5.1.1/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -stdlib=libc++ -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -F/Users/anthonypray/Qt/5.1.1/clang_64/lib -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework QtGui -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/anthonypray/Qt/5.1.1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qml/Life/timerhander.cpp \
		qtquick2applicationviewer/qtquick2applicationviewer.cpp moc_qtquick2applicationviewer.cpp \
		moc_timerhander.cpp
OBJECTS       = main.o \
		timerhander.o \
		qtquick2applicationviewer.o \
		moc_qtquick2applicationviewer.o \
		moc_timerhander.o
DIST          = ../Qt/5.1.1/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.1.1/clang_64/mkspecs/qdevice.pri \
		../Qt/5.1.1/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.1.1/clang_64/mkspecs/common/shell-unix.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/unix.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/mac.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/macx.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/clang.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.1.1/clang_64/mkspecs/qconfig.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.1.1/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.1.1/clang_64/mkspecs/features/spec_post.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf \
		qtquick2applicationviewer/qtquick2applicationviewer.pri \
		../Qt/5.1.1/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/c++11.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/declarative_debug.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/qt.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/resources.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/moc.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/lex.prf \
		QTLife.pro \
		QTLife.pro
QMAKE_TARGET  = QTLife
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = QTLife.app/Contents/MacOS/QTLife

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile QTLife.app/Contents/PkgInfo QTLife.app/Contents/Resources/empty.lproj QTLife.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d QTLife.app/Contents/MacOS/ || mkdir -p QTLife.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QTLife.pro ../Qt/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf ../Qt/5.1.1/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.1.1/clang_64/mkspecs/qdevice.pri \
		../Qt/5.1.1/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.1.1/clang_64/mkspecs/common/shell-unix.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/unix.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/mac.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/macx.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/clang.conf \
		../Qt/5.1.1/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.1.1/clang_64/mkspecs/qconfig.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.1.1/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.1.1/clang_64/mkspecs/features/spec_post.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf \
		qtquick2applicationviewer/qtquick2applicationviewer.pri \
		../Qt/5.1.1/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/c++11.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/declarative_debug.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/qt.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/resources.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/moc.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.1.1/clang_64/mkspecs/features/lex.prf \
		QTLife.pro \
		/Users/anthonypray/Qt/5.1.1/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/anthonypray/Qt/5.1.1/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/anthonypray/Qt/5.1.1/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/anthonypray/Qt/5.1.1/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/anthonypray/Qt/5.1.1/clang_64/lib/QtGui.framework/QtGui.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile QTLife.pro
../Qt/5.1.1/clang_64/mkspecs/features/spec_pre.prf:
../Qt/5.1.1/clang_64/mkspecs/qdevice.pri:
../Qt/5.1.1/clang_64/mkspecs/features/device_config.prf:
../Qt/5.1.1/clang_64/mkspecs/common/shell-unix.conf:
../Qt/5.1.1/clang_64/mkspecs/common/unix.conf:
../Qt/5.1.1/clang_64/mkspecs/common/mac.conf:
../Qt/5.1.1/clang_64/mkspecs/common/macx.conf:
../Qt/5.1.1/clang_64/mkspecs/common/gcc-base.conf:
../Qt/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt/5.1.1/clang_64/mkspecs/common/clang.conf:
../Qt/5.1.1/clang_64/mkspecs/common/clang-mac.conf:
../Qt/5.1.1/clang_64/mkspecs/qconfig.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.1.1/clang_64/mkspecs/features/qt_functions.prf:
../Qt/5.1.1/clang_64/mkspecs/features/qt_config.prf:
../Qt/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf:
../Qt/5.1.1/clang_64/mkspecs/features/spec_post.prf:
../Qt/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.1.1/clang_64/mkspecs/features/default_pre.prf:
../Qt/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf:
../Qt/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf:
qtquick2applicationviewer/qtquick2applicationviewer.pri:
../Qt/5.1.1/clang_64/mkspecs/features/resolve_config.prf:
../Qt/5.1.1/clang_64/mkspecs/features/default_post.prf:
../Qt/5.1.1/clang_64/mkspecs/features/c++11.prf:
../Qt/5.1.1/clang_64/mkspecs/features/mac/sdk.prf:
../Qt/5.1.1/clang_64/mkspecs/features/mac/default_post.prf:
../Qt/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt/5.1.1/clang_64/mkspecs/features/qml_debug.prf:
../Qt/5.1.1/clang_64/mkspecs/features/declarative_debug.prf:
../Qt/5.1.1/clang_64/mkspecs/features/warn_on.prf:
../Qt/5.1.1/clang_64/mkspecs/features/qt.prf:
../Qt/5.1.1/clang_64/mkspecs/features/resources.prf:
../Qt/5.1.1/clang_64/mkspecs/features/moc.prf:
../Qt/5.1.1/clang_64/mkspecs/features/unix/opengl.prf:
../Qt/5.1.1/clang_64/mkspecs/features/unix/thread.prf:
../Qt/5.1.1/clang_64/mkspecs/features/mac/rez.prf:
../Qt/5.1.1/clang_64/mkspecs/features/testcase_targets.prf:
../Qt/5.1.1/clang_64/mkspecs/features/exceptions.prf:
../Qt/5.1.1/clang_64/mkspecs/features/yacc.prf:
../Qt/5.1.1/clang_64/mkspecs/features/lex.prf:
QTLife.pro:
/Users/anthonypray/Qt/5.1.1/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/anthonypray/Qt/5.1.1/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/anthonypray/Qt/5.1.1/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/anthonypray/Qt/5.1.1/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/anthonypray/Qt/5.1.1/clang_64/lib/QtGui.framework/QtGui.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile QTLife.pro

qmake_all: FORCE

QTLife.app/Contents/PkgInfo: 
	@test -d QTLife.app/Contents || mkdir -p QTLife.app/Contents
	@$(DEL_FILE) QTLife.app/Contents/PkgInfo
	@echo "APPL????" >QTLife.app/Contents/PkgInfo
QTLife.app/Contents/Resources/empty.lproj: 
	@test -d QTLife.app/Contents/Resources || mkdir -p QTLife.app/Contents/Resources
	@touch QTLife.app/Contents/Resources/empty.lproj
	
QTLife.app/Contents/Info.plist: 
	@test -d QTLife.app/Contents || mkdir -p QTLife.app/Contents
	@$(DEL_FILE) QTLife.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,QTLife,g" -e "s,@TYPEINFO@,????,g" ../Qt/5.1.1/clang_64/mkspecs/macx-clang/Info.plist.app >QTLife.app/Contents/Info.plist
dist: 
	@test -d .tmp/QTLife1.0.0 || mkdir -p .tmp/QTLife1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QTLife1.0.0/ && $(COPY_FILE) --parents qtquick2applicationviewer/qtquick2applicationviewer.h qml/Life/timerhander.h .tmp/QTLife1.0.0/ && $(COPY_FILE) --parents main.cpp qml/Life/timerhander.cpp qtquick2applicationviewer/qtquick2applicationviewer.cpp .tmp/QTLife1.0.0/ && (cd `dirname .tmp/QTLife1.0.0` && $(TAR) QTLife1.0.0.tar QTLife1.0.0 && $(COMPRESS) QTLife1.0.0.tar) && $(MOVE) `dirname .tmp/QTLife1.0.0`/QTLife1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QTLife1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r QTLife.app
	-$(DEL_FILE) Makefile


first: $(first) copydeploymentfolders

copydeploymentfolders:
	@echo Copying application data... && $(MKDIR) "/Users/anthonypray/QTLife/QTLife.app/Contents/Resources/qml" && $(COPY_DIR) "/Users/anthonypray/QTLife/qml/Life" "/Users/anthonypray/QTLife/QTLife.app/Contents/Resources/qml"

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_qtquick2applicationviewer.cpp moc_timerhander.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qtquick2applicationviewer.cpp moc_timerhander.cpp
moc_qtquick2applicationviewer.cpp: ../Qt/5.1.1/clang_64/include/QtQuick/QQuickView \
		../Qt/5.1.1/clang_64/include/QtQuick/qquickview.h \
		../Qt/5.1.1/clang_64/include/QtQuick/qquickwindow.h \
		../Qt/5.1.1/clang_64/include/QtQuick/qtquickglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/qglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/qconfig.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfeatures.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		../Qt/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmutex.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlogging.h \
		../Qt/5.1.1/clang_64/include/QtCore/qflags.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmetatype.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbytearray.h \
		../Qt/5.1.1/clang_64/include/QtCore/qrefcount.h \
		../Qt/5.1.1/clang_64/include/QtCore/qnamespace.h \
		../Qt/5.1.1/clang_64/include/QtCore/qarraydata.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstring.h \
		../Qt/5.1.1/clang_64/include/QtCore/qchar.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringbuilder.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvarlengtharray.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcontainerfwd.h \
		../Qt/5.1.1/clang_64/include/QtCore/qalgorithms.h \
		../Qt/5.1.1/clang_64/include/QtCore/qisenum.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobjectdefs.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.1.1/clang_64/include/QtGui/qopengl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qt_windows.h \
		../Qt/5.1.1/clang_64/include/QtGui/qopengles2ext.h \
		../Qt/5.1.1/clang_64/include/QtGui/qopenglext.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindow.h \
		../Qt/5.1.1/clang_64/include/QtCore/QObject \
		../Qt/5.1.1/clang_64/include/QtCore/qobject.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qiterator.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcoreevent.h \
		../Qt/5.1.1/clang_64/include/QtCore/qscopedpointer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobject_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/QEvent \
		../Qt/5.1.1/clang_64/include/QtCore/QMargins \
		../Qt/5.1.1/clang_64/include/QtCore/qmargins.h \
		../Qt/5.1.1/clang_64/include/QtCore/qrect.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsize.h \
		../Qt/5.1.1/clang_64/include/QtCore/qpoint.h \
		../Qt/5.1.1/clang_64/include/QtCore/QRect \
		../Qt/5.1.1/clang_64/include/QtGui/qsurface.h \
		../Qt/5.1.1/clang_64/include/QtGui/qsurfaceformat.h \
		../Qt/5.1.1/clang_64/include/QtCore/qpair.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindowdefs.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindowdefs_win.h \
		../Qt/5.1.1/clang_64/include/QtGui/qicon.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpixmap.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpaintdevice.h \
		../Qt/5.1.1/clang_64/include/QtGui/qcolor.h \
		../Qt/5.1.1/clang_64/include/QtGui/qrgb.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringlist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qdatastream.h \
		../Qt/5.1.1/clang_64/include/QtCore/qiodevice.h \
		../Qt/5.1.1/clang_64/include/QtCore/qregexp.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringmatcher.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsharedpointer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qshareddata.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qhash.h \
		../Qt/5.1.1/clang_64/include/QtGui/qimage.h \
		../Qt/5.1.1/clang_64/include/QtGui/qtransform.h \
		../Qt/5.1.1/clang_64/include/QtGui/qmatrix.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpolygon.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvector.h \
		../Qt/5.1.1/clang_64/include/QtGui/qregion.h \
		../Qt/5.1.1/clang_64/include/QtCore/qline.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpainterpath.h \
		../Qt/5.1.1/clang_64/include/QtGui/qcursor.h \
		../Qt/5.1.1/clang_64/include/QtGui/qevent.h \
		../Qt/5.1.1/clang_64/include/QtGui/qkeysequence.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvariant.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmap.h \
		../Qt/5.1.1/clang_64/include/QtCore/qdebug.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtextstream.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlocale.h \
		../Qt/5.1.1/clang_64/include/QtCore/qset.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcontiguouscache.h \
		../Qt/5.1.1/clang_64/include/QtCore/qurl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qurlquery.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfile.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfiledevice.h \
		../Qt/5.1.1/clang_64/include/QtGui/qvector2d.h \
		../Qt/5.1.1/clang_64/include/QtGui/qtouchdevice.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmldebug.h \
		../Qt/5.1.1/clang_64/include/QtQml/qtqmlglobal.h \
		qtquick2applicationviewer/qtquick2applicationviewer.h
	/Users/anthonypray/Qt/5.1.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) qtquick2applicationviewer/qtquick2applicationviewer.h -o moc_qtquick2applicationviewer.cpp

moc_timerhander.cpp: ../Qt/5.1.1/clang_64/include/QtQuick/QQuickItem \
		../Qt/5.1.1/clang_64/include/QtQuick/qquickitem.h \
		../Qt/5.1.1/clang_64/include/QtQuick/qtquickglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/qglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/qconfig.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfeatures.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		../Qt/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmutex.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlogging.h \
		../Qt/5.1.1/clang_64/include/QtCore/qflags.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqml.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlprivate.h \
		../Qt/5.1.1/clang_64/include/QtQml/qtqmlglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvariant.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbytearray.h \
		../Qt/5.1.1/clang_64/include/QtCore/qrefcount.h \
		../Qt/5.1.1/clang_64/include/QtCore/qnamespace.h \
		../Qt/5.1.1/clang_64/include/QtCore/qarraydata.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstring.h \
		../Qt/5.1.1/clang_64/include/QtCore/qchar.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringbuilder.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qalgorithms.h \
		../Qt/5.1.1/clang_64/include/QtCore/qiterator.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmetatype.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvarlengtharray.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcontainerfwd.h \
		../Qt/5.1.1/clang_64/include/QtCore/qisenum.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobjectdefs.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmap.h \
		../Qt/5.1.1/clang_64/include/QtCore/qpair.h \
		../Qt/5.1.1/clang_64/include/QtCore/qdebug.h \
		../Qt/5.1.1/clang_64/include/QtCore/qhash.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtextstream.h \
		../Qt/5.1.1/clang_64/include/QtCore/qiodevice.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobject.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcoreevent.h \
		../Qt/5.1.1/clang_64/include/QtCore/qscopedpointer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobject_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlocale.h \
		../Qt/5.1.1/clang_64/include/QtCore/qshareddata.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvector.h \
		../Qt/5.1.1/clang_64/include/QtCore/qpoint.h \
		../Qt/5.1.1/clang_64/include/QtCore/qset.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcontiguouscache.h \
		../Qt/5.1.1/clang_64/include/QtCore/qurl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qurlquery.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringlist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qdatastream.h \
		../Qt/5.1.1/clang_64/include/QtCore/qregexp.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringmatcher.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlparserstatus.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlpropertyvaluesource.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmllist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmetaobject.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlcomponent.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlerror.h \
		../Qt/5.1.1/clang_64/include/QtQml/qjsvalue.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsharedpointer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/QObject \
		../Qt/5.1.1/clang_64/include/QtCore/QList \
		../Qt/5.1.1/clang_64/include/QtGui/qevent.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindowdefs.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindowdefs_win.h \
		../Qt/5.1.1/clang_64/include/QtGui/qregion.h \
		../Qt/5.1.1/clang_64/include/QtCore/qrect.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsize.h \
		../Qt/5.1.1/clang_64/include/QtGui/qkeysequence.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfile.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfiledevice.h \
		../Qt/5.1.1/clang_64/include/QtGui/qvector2d.h \
		../Qt/5.1.1/clang_64/include/QtGui/qtouchdevice.h \
		../Qt/5.1.1/clang_64/include/QtGui/qfont.h \
		../Qt/5.1.1/clang_64/include/QtGui/qaccessible.h \
		../Qt/5.1.1/clang_64/include/QtGui/qcolor.h \
		../Qt/5.1.1/clang_64/include/QtGui/qrgb.h \
		../Qt/5.1.1/clang_64/include/QtCore/QTimer \
		../Qt/5.1.1/clang_64/include/QtCore/qtimer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbasictimer.h \
		../Qt/5.1.1/clang_64/include/QtCore/QThread \
		../Qt/5.1.1/clang_64/include/QtCore/qthread.h \
		qml/Life/timerhander.h
	/Users/anthonypray/Qt/5.1.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) qml/Life/timerhander.h -o moc_timerhander.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../Qt/5.1.1/clang_64/include/QtGui/QGuiApplication \
		../Qt/5.1.1/clang_64/include/QtGui/qguiapplication.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcoreapplication.h \
		../Qt/5.1.1/clang_64/include/QtCore/qglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/qconfig.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfeatures.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		../Qt/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmutex.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlogging.h \
		../Qt/5.1.1/clang_64/include/QtCore/qflags.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstring.h \
		../Qt/5.1.1/clang_64/include/QtCore/qchar.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbytearray.h \
		../Qt/5.1.1/clang_64/include/QtCore/qrefcount.h \
		../Qt/5.1.1/clang_64/include/QtCore/qnamespace.h \
		../Qt/5.1.1/clang_64/include/QtCore/qarraydata.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringbuilder.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobject.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobjectdefs.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qalgorithms.h \
		../Qt/5.1.1/clang_64/include/QtCore/qiterator.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcoreevent.h \
		../Qt/5.1.1/clang_64/include/QtCore/qscopedpointer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmetatype.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvarlengtharray.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcontainerfwd.h \
		../Qt/5.1.1/clang_64/include/QtCore/qisenum.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobject_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qeventloop.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindowdefs.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindowdefs_win.h \
		../Qt/5.1.1/clang_64/include/QtGui/qinputmethod.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlocale.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvariant.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmap.h \
		../Qt/5.1.1/clang_64/include/QtCore/qpair.h \
		../Qt/5.1.1/clang_64/include/QtCore/qdebug.h \
		../Qt/5.1.1/clang_64/include/QtCore/qhash.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtextstream.h \
		../Qt/5.1.1/clang_64/include/QtCore/qiodevice.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvector.h \
		../Qt/5.1.1/clang_64/include/QtCore/qpoint.h \
		../Qt/5.1.1/clang_64/include/QtCore/qset.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcontiguouscache.h \
		../Qt/5.1.1/clang_64/include/QtCore/qshareddata.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsize.h \
		qtquick2applicationviewer/qtquick2applicationviewer.h \
		../Qt/5.1.1/clang_64/include/QtQuick/QQuickView \
		../Qt/5.1.1/clang_64/include/QtQuick/qquickview.h \
		../Qt/5.1.1/clang_64/include/QtQuick/qquickwindow.h \
		../Qt/5.1.1/clang_64/include/QtQuick/qtquickglobal.h \
		../Qt/5.1.1/clang_64/include/QtGui/qopengl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qt_windows.h \
		../Qt/5.1.1/clang_64/include/QtGui/qopengles2ext.h \
		../Qt/5.1.1/clang_64/include/QtGui/qopenglext.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindow.h \
		../Qt/5.1.1/clang_64/include/QtCore/QObject \
		../Qt/5.1.1/clang_64/include/QtCore/QEvent \
		../Qt/5.1.1/clang_64/include/QtCore/QMargins \
		../Qt/5.1.1/clang_64/include/QtCore/qmargins.h \
		../Qt/5.1.1/clang_64/include/QtCore/qrect.h \
		../Qt/5.1.1/clang_64/include/QtCore/QRect \
		../Qt/5.1.1/clang_64/include/QtGui/qsurface.h \
		../Qt/5.1.1/clang_64/include/QtGui/qsurfaceformat.h \
		../Qt/5.1.1/clang_64/include/QtGui/qicon.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpixmap.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpaintdevice.h \
		../Qt/5.1.1/clang_64/include/QtGui/qcolor.h \
		../Qt/5.1.1/clang_64/include/QtGui/qrgb.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringlist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qdatastream.h \
		../Qt/5.1.1/clang_64/include/QtCore/qregexp.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringmatcher.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsharedpointer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.1.1/clang_64/include/QtGui/qimage.h \
		../Qt/5.1.1/clang_64/include/QtGui/qtransform.h \
		../Qt/5.1.1/clang_64/include/QtGui/qmatrix.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpolygon.h \
		../Qt/5.1.1/clang_64/include/QtGui/qregion.h \
		../Qt/5.1.1/clang_64/include/QtCore/qline.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpainterpath.h \
		../Qt/5.1.1/clang_64/include/QtGui/qcursor.h \
		../Qt/5.1.1/clang_64/include/QtGui/qevent.h \
		../Qt/5.1.1/clang_64/include/QtGui/qkeysequence.h \
		../Qt/5.1.1/clang_64/include/QtCore/qurl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qurlquery.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfile.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfiledevice.h \
		../Qt/5.1.1/clang_64/include/QtGui/qvector2d.h \
		../Qt/5.1.1/clang_64/include/QtGui/qtouchdevice.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmldebug.h \
		../Qt/5.1.1/clang_64/include/QtQml/qtqmlglobal.h \
		qml/Life/timerhander.h \
		../Qt/5.1.1/clang_64/include/QtQuick/QQuickItem \
		../Qt/5.1.1/clang_64/include/QtQuick/qquickitem.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqml.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlprivate.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlparserstatus.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlpropertyvaluesource.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmllist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmetaobject.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlcomponent.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlerror.h \
		../Qt/5.1.1/clang_64/include/QtQml/qjsvalue.h \
		../Qt/5.1.1/clang_64/include/QtCore/QList \
		../Qt/5.1.1/clang_64/include/QtGui/qfont.h \
		../Qt/5.1.1/clang_64/include/QtGui/qaccessible.h \
		../Qt/5.1.1/clang_64/include/QtCore/QTimer \
		../Qt/5.1.1/clang_64/include/QtCore/qtimer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbasictimer.h \
		../Qt/5.1.1/clang_64/include/QtCore/QThread \
		../Qt/5.1.1/clang_64/include/QtCore/qthread.h \
		../Qt/5.1.1/clang_64/include/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

timerhander.o: qml/Life/timerhander.cpp qml/Life/timerhander.h \
		../Qt/5.1.1/clang_64/include/QtQuick/QQuickItem \
		../Qt/5.1.1/clang_64/include/QtQuick/qquickitem.h \
		../Qt/5.1.1/clang_64/include/QtQuick/qtquickglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/qglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/qconfig.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfeatures.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		../Qt/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmutex.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlogging.h \
		../Qt/5.1.1/clang_64/include/QtCore/qflags.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqml.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlprivate.h \
		../Qt/5.1.1/clang_64/include/QtQml/qtqmlglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvariant.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbytearray.h \
		../Qt/5.1.1/clang_64/include/QtCore/qrefcount.h \
		../Qt/5.1.1/clang_64/include/QtCore/qnamespace.h \
		../Qt/5.1.1/clang_64/include/QtCore/qarraydata.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstring.h \
		../Qt/5.1.1/clang_64/include/QtCore/qchar.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringbuilder.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qalgorithms.h \
		../Qt/5.1.1/clang_64/include/QtCore/qiterator.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmetatype.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvarlengtharray.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcontainerfwd.h \
		../Qt/5.1.1/clang_64/include/QtCore/qisenum.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobjectdefs.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmap.h \
		../Qt/5.1.1/clang_64/include/QtCore/qpair.h \
		../Qt/5.1.1/clang_64/include/QtCore/qdebug.h \
		../Qt/5.1.1/clang_64/include/QtCore/qhash.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtextstream.h \
		../Qt/5.1.1/clang_64/include/QtCore/qiodevice.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobject.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcoreevent.h \
		../Qt/5.1.1/clang_64/include/QtCore/qscopedpointer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobject_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlocale.h \
		../Qt/5.1.1/clang_64/include/QtCore/qshareddata.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvector.h \
		../Qt/5.1.1/clang_64/include/QtCore/qpoint.h \
		../Qt/5.1.1/clang_64/include/QtCore/qset.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcontiguouscache.h \
		../Qt/5.1.1/clang_64/include/QtCore/qurl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qurlquery.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringlist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qdatastream.h \
		../Qt/5.1.1/clang_64/include/QtCore/qregexp.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringmatcher.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlparserstatus.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlpropertyvaluesource.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmllist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmetaobject.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlcomponent.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlerror.h \
		../Qt/5.1.1/clang_64/include/QtQml/qjsvalue.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsharedpointer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/QObject \
		../Qt/5.1.1/clang_64/include/QtCore/QList \
		../Qt/5.1.1/clang_64/include/QtGui/qevent.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindowdefs.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindowdefs_win.h \
		../Qt/5.1.1/clang_64/include/QtGui/qregion.h \
		../Qt/5.1.1/clang_64/include/QtCore/qrect.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsize.h \
		../Qt/5.1.1/clang_64/include/QtGui/qkeysequence.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfile.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfiledevice.h \
		../Qt/5.1.1/clang_64/include/QtGui/qvector2d.h \
		../Qt/5.1.1/clang_64/include/QtGui/qtouchdevice.h \
		../Qt/5.1.1/clang_64/include/QtGui/qfont.h \
		../Qt/5.1.1/clang_64/include/QtGui/qaccessible.h \
		../Qt/5.1.1/clang_64/include/QtGui/qcolor.h \
		../Qt/5.1.1/clang_64/include/QtGui/qrgb.h \
		../Qt/5.1.1/clang_64/include/QtCore/QTimer \
		../Qt/5.1.1/clang_64/include/QtCore/qtimer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbasictimer.h \
		../Qt/5.1.1/clang_64/include/QtCore/QThread \
		../Qt/5.1.1/clang_64/include/QtCore/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timerhander.o qml/Life/timerhander.cpp

qtquick2applicationviewer.o: qtquick2applicationviewer/qtquick2applicationviewer.cpp qtquick2applicationviewer/qtquick2applicationviewer.h \
		../Qt/5.1.1/clang_64/include/QtQuick/QQuickView \
		../Qt/5.1.1/clang_64/include/QtQuick/qquickview.h \
		../Qt/5.1.1/clang_64/include/QtQuick/qquickwindow.h \
		../Qt/5.1.1/clang_64/include/QtQuick/qtquickglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/qglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/qconfig.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfeatures.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsystemdetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcompilerdetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qprocessordetection.h \
		../Qt/5.1.1/clang_64/include/QtCore/qglobalstatic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbasicatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.1.1/clang_64/include/QtCore/qgenericatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_msvc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_integrity.h \
		../Qt/5.1.1/clang_64/include/QtCore/qoldbasicatomic.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_vxworks.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_power.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_alpha.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv7.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv6.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_armv5.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_bfin.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_ia64.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_mips.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_s390.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_sh4a.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_sparc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_x86.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_cxx11.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_gcc.h \
		../Qt/5.1.1/clang_64/include/QtCore/qatomic_unix.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmutex.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlogging.h \
		../Qt/5.1.1/clang_64/include/QtCore/qflags.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtypeinfo.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtypetraits.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsysinfo.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmetatype.h \
		../Qt/5.1.1/clang_64/include/QtCore/qbytearray.h \
		../Qt/5.1.1/clang_64/include/QtCore/qrefcount.h \
		../Qt/5.1.1/clang_64/include/QtCore/qnamespace.h \
		../Qt/5.1.1/clang_64/include/QtCore/qarraydata.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstring.h \
		../Qt/5.1.1/clang_64/include/QtCore/qchar.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringbuilder.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvarlengtharray.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcontainerfwd.h \
		../Qt/5.1.1/clang_64/include/QtCore/qalgorithms.h \
		../Qt/5.1.1/clang_64/include/QtCore/qisenum.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobjectdefs.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.1.1/clang_64/include/QtGui/qopengl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qt_windows.h \
		../Qt/5.1.1/clang_64/include/QtGui/qopengles2ext.h \
		../Qt/5.1.1/clang_64/include/QtGui/qopenglext.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindow.h \
		../Qt/5.1.1/clang_64/include/QtCore/QObject \
		../Qt/5.1.1/clang_64/include/QtCore/qobject.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qiterator.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcoreevent.h \
		../Qt/5.1.1/clang_64/include/QtCore/qscopedpointer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qobject_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/QEvent \
		../Qt/5.1.1/clang_64/include/QtCore/QMargins \
		../Qt/5.1.1/clang_64/include/QtCore/qmargins.h \
		../Qt/5.1.1/clang_64/include/QtCore/qrect.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsize.h \
		../Qt/5.1.1/clang_64/include/QtCore/qpoint.h \
		../Qt/5.1.1/clang_64/include/QtCore/QRect \
		../Qt/5.1.1/clang_64/include/QtGui/qsurface.h \
		../Qt/5.1.1/clang_64/include/QtGui/qsurfaceformat.h \
		../Qt/5.1.1/clang_64/include/QtCore/qpair.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindowdefs.h \
		../Qt/5.1.1/clang_64/include/QtGui/qwindowdefs_win.h \
		../Qt/5.1.1/clang_64/include/QtGui/qicon.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpixmap.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpaintdevice.h \
		../Qt/5.1.1/clang_64/include/QtGui/qcolor.h \
		../Qt/5.1.1/clang_64/include/QtGui/qrgb.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringlist.h \
		../Qt/5.1.1/clang_64/include/QtCore/qdatastream.h \
		../Qt/5.1.1/clang_64/include/QtCore/qiodevice.h \
		../Qt/5.1.1/clang_64/include/QtCore/qregexp.h \
		../Qt/5.1.1/clang_64/include/QtCore/qstringmatcher.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsharedpointer.h \
		../Qt/5.1.1/clang_64/include/QtCore/qshareddata.h \
		../Qt/5.1.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qhash.h \
		../Qt/5.1.1/clang_64/include/QtGui/qimage.h \
		../Qt/5.1.1/clang_64/include/QtGui/qtransform.h \
		../Qt/5.1.1/clang_64/include/QtGui/qmatrix.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpolygon.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvector.h \
		../Qt/5.1.1/clang_64/include/QtGui/qregion.h \
		../Qt/5.1.1/clang_64/include/QtCore/qline.h \
		../Qt/5.1.1/clang_64/include/QtGui/qpainterpath.h \
		../Qt/5.1.1/clang_64/include/QtGui/qcursor.h \
		../Qt/5.1.1/clang_64/include/QtGui/qevent.h \
		../Qt/5.1.1/clang_64/include/QtGui/qkeysequence.h \
		../Qt/5.1.1/clang_64/include/QtCore/qvariant.h \
		../Qt/5.1.1/clang_64/include/QtCore/qmap.h \
		../Qt/5.1.1/clang_64/include/QtCore/qdebug.h \
		../Qt/5.1.1/clang_64/include/QtCore/qtextstream.h \
		../Qt/5.1.1/clang_64/include/QtCore/qlocale.h \
		../Qt/5.1.1/clang_64/include/QtCore/qset.h \
		../Qt/5.1.1/clang_64/include/QtCore/qcontiguouscache.h \
		../Qt/5.1.1/clang_64/include/QtCore/qurl.h \
		../Qt/5.1.1/clang_64/include/QtCore/qurlquery.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfile.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfiledevice.h \
		../Qt/5.1.1/clang_64/include/QtGui/qvector2d.h \
		../Qt/5.1.1/clang_64/include/QtGui/qtouchdevice.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmldebug.h \
		../Qt/5.1.1/clang_64/include/QtQml/qtqmlglobal.h \
		../Qt/5.1.1/clang_64/include/QtCore/QCoreApplication \
		../Qt/5.1.1/clang_64/include/QtCore/qcoreapplication.h \
		../Qt/5.1.1/clang_64/include/QtCore/qeventloop.h \
		../Qt/5.1.1/clang_64/include/QtCore/QDir \
		../Qt/5.1.1/clang_64/include/QtCore/qdir.h \
		../Qt/5.1.1/clang_64/include/QtCore/qfileinfo.h \
		../Qt/5.1.1/clang_64/include/QtQml/QQmlEngine \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlengine.h \
		../Qt/5.1.1/clang_64/include/QtQml/qjsengine.h \
		../Qt/5.1.1/clang_64/include/QtQml/qjsvalue.h \
		../Qt/5.1.1/clang_64/include/QtQml/qqmlerror.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtquick2applicationviewer.o qtquick2applicationviewer/qtquick2applicationviewer.cpp

moc_qtquick2applicationviewer.o: moc_qtquick2applicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtquick2applicationviewer.o moc_qtquick2applicationviewer.cpp

moc_timerhander.o: moc_timerhander.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timerhander.o moc_timerhander.cpp

####### Install

install_itemfolder_01: first FORCE
	@test -d $(INSTALL_ROOT)/opt/QTLife/qml || mkdir -p $(INSTALL_ROOT)/opt/QTLife/qml
	-$(INSTALL_DIR) /Users/anthonypray/QTLife/qml/Life $(INSTALL_ROOT)/opt/QTLife/qml/

uninstall_itemfolder_01: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/QTLife/qml/Life
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/QTLife/qml/ 


install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/QTLife/bin || mkdir -p $(INSTALL_ROOT)/opt/QTLife/bin
	$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/QTLife/bin/QTLife.app"
	
	-$(INSTALL_DIR) "QTLife.app" "$(INSTALL_ROOT)/opt/QTLife/bin/QTLife.app"

uninstall_target: FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/QTLife/bin/QTLife.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/QTLife/bin/ 


install:  install_itemfolder_01 install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_target   FORCE

FORCE:

